### ISSUE TITLE
Issue with ToStringExtensions.ToCompactDateString()

### ISSUE THREAD

**Issue by sstoenner** [PeterHuberSg/StorageLib#1]
Hello Peter... While running your tests I found that a test comparing dates failed and then I looked to find the reason and found the above mentioned function was using an EXACT date format to create a short date string...
Well, this may be fine where you live but it caused a test to fail over here...
So, why not just use the built-in ToShortDateString() function to create the short date string? This function accounts for different cultures.

**Comment by PeterHuberSg** [comment]
Thanks for trying out `StorageLib`. 

I think `ToStringExtensions.ToCompactDateString()` is an old method, which is no longer used in `StorageLib`, but the test is still there. You can comment `ToStringExtensions.ToCompactDateString()` and its tests out and everything else should be working fine.

However, I don't know why the test fails:

    public static string DateFormat = "dd.MM.yyyy";

    public static string ToCompactDateString(this DateTime date) {
      string returnString = date.Date.ToString(CsvConfig.DateFormat);
      if (returnString[3]=='0') returnString = returnString.Substring(0, 3) + returnString[4..];

      if (returnString[0]=='0') returnString = returnString[1..];

      return returnString;
    }

It doesn't really matter why, but I am curious anyhow.

**Comment by sstoenner** [comment]
The problem is that your Csv.ParseDateTime and Csv.ParseDateTimeNull functions do NOT use the same exact date format as your ToCompactDateString function to convert a date string BACK to DateTime - they just use the current thread culture to get the expected string format which is NOT the same in other countries as the format that you were using.

**Comment by PeterHuberSg** [comment]
Ok, found it. The problems is not `ToStringExtensions.ToCompactDateString()`, which writes the date exactly in the form intended, the problem is `DateTime.TryParse(field, out var value)`, where I try to read that value, but don't tell `TryParse `which culture to use.

For performance reasons, I prefer to write the date in a particular form regardless of culture and I wrote my one methods for writing `CsvWriter.WriteDate()` and reading `CsvReader.ReadDate()`, which replaced `ToStringExtensions.ToCompactDateString()` and `DateTime.TryParse()`.

Since  `ToStringExtensions.ToCompactDateString()` and `DateTime.TryParse(field, out var value)` are no longer used for anything, can you please comment them out, also their unit test CsvTest.assertDate(), etc. and then see if any other unit test produce an error ? 

I commented them already out in StorageLib on GitHub.
